name: Multi-Platform Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux 目标
          - os: ubuntu-latest
            arch: x86_64
            cc: gcc
            output: hello_linux_amd64
          - os: ubuntu-latest
            arch: arm64
            cc: gcc
            output: hello_linux_arm64
          
          # Windows 目标
          - os: windows-latest
            arch: x86_64
            cc: x86_64-w64-mingw32-gcc
            output: hello_windows_amd64.exe
          - os: windows-latest
            arch: aarch64
            cc: aarch64-w64-mingw32-gcc
            output: hello_windows_arm64.exe

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64
          
      - name: Compile
        run: |
          ${{ matrix.cc }} hello.c -o ${{ matrix.output }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          
  release:
    name: Create Release
    needs: build  # 依赖 build 任务
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 使用触发的标签
          name: Release ${{ github.ref_name }}
          body: |
            Multi-platform hello world binaries
            - Linux AMD64
            - Linux ARM64
            - Windows AMD64
            - Windows ARM64
          files: |
            artifacts/hello_linux_amd64
            artifacts/hello_linux_arm64
            artifacts/hello_windows_amd64.exe
            artifacts/hello_windows_arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}