name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux AMD64
          - os: ubuntu-latest
            arch: x86_64
            cc: gcc
            output: hello_linux_amd64
            artifact: linux-amd64
            
          # Linux ARM64
          - os: ubuntu-latest
            arch: arm64
            cc: gcc
            output: hello_linux_arm64
            artifact: linux-arm64
            
          # Windows AMD64 (交叉编译)
          - os: ubuntu-latest
            arch: x86_64
            cc: x86_64-w64-mingw32-gcc
            output: hello_windows_amd64.exe
            artifact: windows-amd64
            
          # Windows ARM64 (交叉编译)
          - os: ubuntu-latest
            arch: aarch64
            cc: aarch64-w64-mingw32-gcc
            output: hello_windows_arm64.exe
            artifact: windows-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64
          
      - name: Compile ${{ matrix.artifact }}
        run: |
          ${{ matrix.cc }} hello.c -o ${{ matrix.output }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.output }}
          
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: List artifacts
        run: ls -R artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Hello World Release
            
            Multi-platform binaries for:
            
            | 平台       | 架构  | 文件名                      |
            |------------|-------|-----------------------------|
            | Linux      | AMD64 | `hello_linux_amd64`         |
            | Linux      | ARM64 | `hello_linux_arm64`         |
            | Windows    | AMD64 | `hello_windows_amd64.exe`   |
            | Windows    | ARM64 | `hello_windows_arm64.exe`   |
            
            ### 使用说明
            1. Linux: `chmod +x hello_linux_* && ./hello_linux_*`
            2. Windows: 双击可执行文件或在终端运行
            
          draft: false
          prerelease: false
          files: |
            artifacts/hello_linux_amd64
            artifacts/hello_linux_arm64
            artifacts/hello_windows_amd64.exe
            artifacts/hello_windows_arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}